=== NzoSifou/ultimate-zpl-viewer/Ultimate ZPL Viewer/Assets/zpl_color_scheme.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ZPL Commands Color Scheme Schema",
  "type": "object",
  "properties": {
    "commandColor": {
      "type": "string",
      "pattern": "^#([0-9A-Fa-f]{3}){1,2}$"
    },
    "parameterColor": {
      "type": "string",
      "pattern": "^#([0-9A-Fa-f]{3}){1,2}$"
    },
    "textColor": {
      "type": "string",
      "pattern": "^#([0-9A-Fa-f]{3}){1,2}$"
    },
    "textParameters": {
      "type": "array",
      "items": { "type": "string" }
    },
    "commands": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "command": {
            "type": "string",
            "pattern": "^(\\^|~)[A-Z][A-Z0-9@]?$"
          },
          "alternativeCommand": {
            "type": "string",
            "pattern": "^~[A-Z][A-Z0-9@]?$"
          },
          "shortDescription": { "type": "string" },
          "description": { "type": "string" },
          "parameters": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": { "type": "string" },
                "description": { "type": "string" },
                "type": {
                  "type": "string",
                  "enum": [ "string", "number" ]
                },
                "required": { "type":  "boolean" }
              },
              "required": [ "name", "description", "type" ]
            }
          }
        },
        "required": [ "command", "shortDescription", "description" ]
      }
    }
  },
  "required": [ "commandColor", "parameterColor", "textColor", "textParameters", "commands" ]
}

=== NzoSifou/ultimate-zpl-viewer/Ultimate ZPL Viewer/Assets/zpl_color_scheme_default.json
{
  "commandColor": "#FF4444",
  "parameterColor": "#4488FF",
  "textColor": "#FFFFFF",
  "textParameters": [
    "data",
    "comment"
  ],
  "commands": [
    {
      "command": "^A",
      "shortDescription": "lang.editor.shortDescription.A",
      "description": "lang.editor.description.A",
      "parameters": [
        {
          "name": "font",
          "description": "lang.editor.parameters.A.font",
          "type": "string",
          "required": true
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.A.height",
          "type": "number"
        },
        {
          "name": "width",
          "description": "lang.editor.parameters.A.width",
          "type": "number"
        }
      ]
    },
    {
      "command": "^A@",
      "shortDescription": "lang.editor.shortDescription.A@",
      "description": "lang.editor.description.A@",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.A@.orientation",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.A@.height",
          "type": "number"
        },
        {
          "name": "width",
          "description": "lang.editor.parameters.A@.width",
          "type": "number"
        },
        {
          "name": "path",
          "description": "lang.editor.parameters.A@.path",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B0",
      "shortDescription": "lang.editor.shortDescription.B0",
      "description": "lang.editor.description.B0",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B0.orientation",
          "type": "string"
        },
        {
          "name": "magnification",
          "description": "lang.editor.parameters.B0.magnification",
          "type": "number"
        },
        {
          "name": "eci",
          "description": "lang.editor.parameters.B0.eci",
          "type": "string"
        },
        {
          "name": "size",
          "description": "lang.editor.parameters.B0.size",
          "type": "number"
        },
        {
          "name": "readerInit",
          "description": "lang.editor.parameters.B0.readerInit",
          "type": "string"
        },
        {
          "name": "symbols",
          "description": "lang.editor.parameters.B0.symbols",
          "type": "number"
        },
        {
          "name": "id",
          "description": "lang.editor.parameters.B0.id",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B1",
      "shortDescription": "lang.editor.shortDescription.B1",
      "description": "lang.editor.description.B1",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B1.orientation",
          "type": "string"
        },
        {
          "name": "checkDigit",
          "description": "lang.editor.parameters.B1.checkDigit",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.B1.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B1.line",
          "type": "string"
        },
        {
          "name": "lineAbove",
          "description": "lang.editor.parameters.B1.lineAbove",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B2",
      "shortDescription": "lang.editor.shortDescription.B2",
      "description": "lang.editor.description.B2",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B2.orientation",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.B2.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B2.line",
          "type": "string"
        },
        {
          "name": "lineAbove",
          "description": "lang.editor.parameters.B2.lineAbove",
          "type": "string"
        },
        {
          "name": "checkDigit",
          "description": "lang.editor.parameters.B2.checkDigit",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B3",
      "shortDescription": "lang.editor.shortDescription.B3",
      "description": "lang.editor.description.B3",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B3.orientation",
          "type": "string"
        },
        {
          "name": "checkDigit",
          "description": "lang.editor.parameters.B3.checkDigit",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.B3.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B3.line",
          "type": "string"
        },
        {
          "name": "lineAbove",
          "description": "lang.editor.parameters.B3.lineAbove",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B4",
      "shortDescription": "lang.editor.shortDescription.B4",
      "description": "lang.editor.description.B4",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B4.orientation",
          "type": "string"
        },
        {
          "name": "heightMultiplier",
          "description": "lang.editor.parameters.B4.heightMultiplier",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B4.line",
          "type": "string"
        },
        {
          "name": "mode",
          "description": "lang.editor.parameters.B4.mode",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B5",
      "shortDescription": "lang.editor.shortDescription.B5",
      "description": "lang.editor.description.B5",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B5.orientation",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.B5.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B5.line",
          "type": "string"
        },
        {
          "name": "lineAbove",
          "description": "lang.editor.parameters.B5.lineAbove",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B7",
      "shortDescription": "lang.editor.shortDescription.B7",
      "description": "lang.editor.description.B7",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B7.orientation",
          "type": "string"
        },
        {
          "name": "rowHeight",
          "description": "lang.editor.parameters.B7.rowHeight",
          "type": "number"
        },
        {
          "name": "security",
          "description": "lang.editor.parameters.B7.security",
          "type": "number"
        },
        {
          "name": "columns",
          "description": "lang.editor.parameters.B7.columns",
          "type": "number"
        },
        {
          "name": "rows",
          "description": "lang.editor.parameters.B7.rows",
          "type": "number"
        },
        {
          "name": "truncate",
          "description": "lang.editor.parameters.B7.truncate",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B8",
      "shortDescription": "lang.editor.shortDescription.B8",
      "description": "lang.editor.description.B8",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B8.orientation",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.B8.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B8.line",
          "type": "string"
        },
        {
          "name": "lineAbove",
          "description": "lang.editor.parameters.B8.lineAbove",
          "type": "string"
        }
      ]
    },
    {
      "command": "^B9",
      "shortDescription": "lang.editor.shortDescription.B9",
      "description": "lang.editor.description.B9",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.B9.orientation",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.B9.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.B9.line",
          "type": "string"
        },
        {
          "name": "lineAbove",
          "description": "lang.editor.parameters.B9.lineAbove",
          "type": "string"
        },
        {
          "name": "checkDigit",
          "description": "lang.editor.parameters.B9.checkDigit",
          "type": "string"
        }
      ]
    },
    {
      "command": "^BA",
      "shortDescription": "lang.editor.shortDescription.BA",
      "description": "lang.editor.description.BA",
      "parameters": [
        {
          "name": "orientation",
          "description": "lang.editor.parameters.BA.orientation",
          "type": "string"
        },
        {
          "name": "height",
          "description": "lang.editor.parameters.BA.height",
          "type": "number"
        },
        {
          "name": "line",
          "description": "lang.editor.parameters.BA.line",
          "type": "string"
